[package]
name = "polocloud-rust-test"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.47.0", features = ["macros", "rt-multi-thread"] }
polocloud-sdk = { path = "../polocloud/sdk/sdk-rust/" }
